language: python

cache: pip

python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

install:
    - pip install -U -r requirements.txt

script:
    - scripts/test

after_script:
    - codecov

jobs:
    include:
        - stage: style
          install: skip
          script:
              - pip install flake8
              - flake8 .
