environment:
  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32

install:

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -m pip install --upgrade pip"
  - "pip install -U -r requirements.txt"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Run the project tests (don't do examples because they are too slow)
  - "pytest"

