site_name: Uvicorn
site_description: The lightning-fast ASGI server.

theme:
  name: "material"
  custom_dir: docs/overrides
  favicon: uvicorn.png
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy


repo_name: encode/uvicorn
repo_url: https://github.com/encode/uvicorn
edit_uri: ""

nav:
  - Home:
    - About: index.md
    - ASGI Interface: "home/asgi.md"
    - Alternative ASGI Servers: "home/alternative_servers.md"
    - ASGI Frameworks: "home/frameworks.md"
  - Settings: "settings.md"
  - Deployment: "deployment.md"
  - Server Behavior: "server-behavior.md"
  - Contributing: "contributing.md"

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - toc:
      permalink: true

extra_javascript:
  - "js/chat.js"
  - "js/sidecar-1.5.0.js"
