version: 1
disable_existing_loggers: False
formatters:
  uvicorn_colored:
    "()": uvicorn.logging.ColourizedFormatter
    format: "%(levelprefix)s %(asctime)s - %(message)s"
    use_colors: True
  uvicorn_access:
    "()": uvicorn.logging.AccessFormatter
    format: '%(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
    use_colors: True
  simple:
    format: "%(levelname)s: %(name)s - %(lineno)d - %(message)s"
handlers:
  console:
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stdout
  uvicorn_colored:
    formatter: uvicorn_colored
    class: logging.StreamHandler
    stream: ext://sys.stdout
  uvicorn_access:
    formatter: uvicorn_access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.access:
    level: INFO
    handlers:
      - uvicorn_access
    propagate: no
  uvicorn.error:
    level: INFO
    handlers:
      - uvicorn_colored
    propagate: no
  uvicorn.asgi:
    level: TRACE
    handlers:
      - uvicorn_colored
    propagate: no
  main:
    level: DEBUG
    handlers:
      - console
    propagate: no