title: "[Potential Issue] "
labels: ["Discuss a possible issue"]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: The issue is reproducible against the latest release.
          required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the issue
      description: |
        Provide a *minimal* example with steps to reproduce the issue locally.
        NOTE: try to keep any external dependencies *at an absolute minimum*.
        In other words, remove anything that doesn't make the bug go away.
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Debugging material
      description: |
        Any tracebacks, screenshots, etc. that can help understanding the problem.
        NOTE:
        - Please list tracebacks in full (don't truncate them).
        - If relevant, consider turning on DEBUG or TRACE logs for additional details (see the Logging section on https://www.uvicorn.org/settings/ specifically the `log-level` flag).
        - Consider using `<details>` to make tracebacks/logs collapsible if they're very large (see https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d).
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Describe your environment.
      placeholder: |
        - OS / Python / Uvicorn version: just run `uvicorn --version`
        - The exact command you're running uvicorn with, all flags you passed included. If you run it with gunicorn please do the same. If there is a reverse-proxy involved and you cannot reproduce without it please give the minimal config of it to reproduce.
    validations:
      required: true
