# This workflow will install Python dependencies, run tests and lint with a matrix of OS and Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, pypy3]
        exclude:
        - os: windows-latest
          python-version: 3.6
        - os: windows-latest
          python-version: pypy3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies windows
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U click h11 wsproto==0.13.* websockets==8.*
        python -m pip install -U autoflake black codecov isort pytest pytest-cov requests watchdog
    - name: Install dependencies pypy3
      if: matrix.python-version == 'pypy3'
      run: |
        python -m pip install --upgrade pip
        pip install -U click h11 wsproto==0.13.*
        pip install -U autoflake codecov isort pytest pytest-cov requests watchdog
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --ignore venv --cov=uvicorn --cov=tests --cov-report=term-missing
    - name: Run coverage
      run: |
        coverage html
    - name: Run autoflake
      run: |
        autoflake --recursive uvicorn tests
    - name: Run black check
      # Skipping 'black' on pypy3.6-7.1.1. See issue https://bitbucket.org/pypy/pypy/issues/2985
      if: matrix.python-version != 'pypy3'
      run: |
        black uvicorn tests --check
    - name: Run codecov
      run: |
        codecov
