---
name: Test Integration

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: nginx_django
      working-directory: ./contrib/tests/nginx_django
      run: |
        chmod +x ./runtests/sh
        ./runtests.sh
