---
name: Test Suite

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-lint
      - name: Install dependencies
        run: pip install black flake8 isort mypy types-click types-PyYAML
      - name: Run black
        run: black --check --diff uvicorn tests
      - name: Run isort
        run: isort --check --diff uvicorn tests
      - name: Run flake
        run: flake8 uvicorn tests
      - name: Check types with mypy
        run: mypy

  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
#      - name: "Build package & docs"
#        run: "scripts/build"
#        shell: bash
      - name: "Run tests"
        run: coverage run -m pytest
        shell: bash
      - name: "Enforce coverage"
        run: coverage report --show-missing --skip-covered --fail-under=90
        shell: bash
