---
name: Test Suite

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            script_install: "scripts/install.sh"
            script_test: "scripts/test.sh"
          - os: ubuntu-latest
            script_install: "scripts/install.sh"
            script_test: "scripts/test.sh"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: "${{ matrix.script_install }}"
        shell: bash
      - name: "Run tests"
        run: "${{ matrix.script_test }}"
        shell: bash
